services:
  app:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    container_name: greenlit_api_app
    volumes:
      - ./:/var/www
    environment:
      APP_URL: http://localhost:8080
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: greenlit
      DB_USERNAME: greenlit
      DB_PASSWORD: secret
      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: cookie
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-greenlit
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: greenlit_api_nginx
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-greenlit
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/api/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

  db:
    image: postgres:16
    container_name: greenlit_api_postgres
    restart: always
    environment:
      POSTGRES_DB: greenlit
      POSTGRES_USER: greenlit
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_HOST:-55432}:5432"
    networks:
      - app-greenlit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greenlit -d greenlit"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: greenlit_api_redis
    ports:
      - "6379:6379"
    
    networks:
      - app-greenlit
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  horizon:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    container_name: greenlit_api_horizon
    working_dir: /var/www
    command: php artisan horizon
    volumes:
      - ./:/var/www
    environment:
      APP_URL: http://localhost:8080
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: greenlit
      DB_USERNAME: greenlit
      DB_PASSWORD: secret
      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: cookie
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    networks:
      - app-greenlit

  soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    container_name: greenlit_api_soketi
    ports:
      - "6001:6001" # WebSocket
    
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID:-greenlit}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY:-app-key}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET:-app-secret}"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: "true"
      SOKETI_DEFAULT_APP_ENABLE_USER_AUTHENTICATION: "true"
    networks:
      - app-greenlit

volumes:
  pgdata:

networks:
  app-greenlit:
    driver: bridge